# Generated by Django 2.2.5 on 2019-10-02 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20190927_1651'), ('api', '0003_auto_20190928_1319'), ('api', '0004_auto_20190928_1332'), ('api', '0005_auto_20190928_1358'), ('api', '0006_auto_20190928_1415'), ('api', '0007_auto_20190928_1631'), ('api', '0008_credentials_date_added'), ('api', '0009_auto_20190928_1734')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreIAPSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='Токен идентификатор сессии')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlayIAPSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('device_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DeviceSession')),
            ],
        ),
        migrations.CreateModel(
            name='AppStoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlayProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=256, verbose_name='IAP SKU (Product ID)')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_play_bundle_id', models.CharField(max_length=256, verbose_name='Play Market Bundle ID')),
                ('google_play_api_key', models.CharField(max_length=256, verbose_name='Google Play API Key')),
                ('appstore_bundle_id', models.CharField(max_length=256, verbose_name='AppStore Bundle ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Credentials',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='AppStoreIAPPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status')),
                ('type', models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16, verbose_name='Type: reward video or purchase')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AppStoreProduct')),
                ('device_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeviceSession')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlayIAPPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status')),
                ('type', models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16, verbose_name='Type: reward video or purchase')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct')),
                ('device_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeviceSession')),
                ('order_id', models.CharField(blank=True, max_length=256)),
                ('purchase_token', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
