# Generated by Django 2.2.5 on 2019-11-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longjob', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Just created'), ('inprogress', 'In progress'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=16)),
                ('result', models.TextField(blank=True)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('ended_time', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, default='ic_notification', max_length=256)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_item', to='longjob.LongJobLog')),
                ('push_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PushSubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
