# Generated by Django 2.2.5 on 2019-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0009_auto_20190928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
