# Generated by Django 2.2.5 on 2019-09-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credentials', 'verbose_name_plural': 'Credentials'},
        ),
    ]
