# Generated by Django 2.2.5 on 2019-11-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pushnotificationqueueitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationqueueitem',
            name='icon',
        ),
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='is_broadcast',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotificationqueueitem',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pushnotificationqueueitem',
            name='push_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PushSubscription'),
        ),
        migrations.AlterField(
            model_name='pushnotificationqueueitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
