# Generated by Django 2.2.5 on 2019-09-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190927_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlayProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='type',
            field=models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='type',
            field=models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16),
        ),
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AppStoreProduct'),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct'),
        ),
    ]
