# Generated by Django 2.2.5 on 2019-10-05 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191002_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
