# Generated by Django 2.2.5 on 2019-09-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190928_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='device_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeviceSession'),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='device_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DeviceSession'),
        ),
    ]
