# Generated by Django 2.2.5 on 2019-10-05 17:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191005_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='server_secret',
            field=models.CharField(default=api.models.generate_secret, max_length=256, verbose_name='Server-only secret'),
        ),
        migrations.AddField(
            model_name='credentials',
            name='shared_secret',
            field=models.CharField(default=api.models.generate_secret, max_length=256, verbose_name='Shared secret'),
        ),
    ]
