# Generated by Django 2.2.5 on 2019-11-13 15:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191113_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='server_secret',
            field=models.CharField(default=api.models.generate_secret, max_length=256, verbose_name='Server-only secret'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='shared_secret',
            field=models.CharField(default=api.models.generate_secret, max_length=256, verbose_name='Shared secret'),
        ),
    ]
