# Generated by Django 2.2.5 on 2019-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191113_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invalid', 'Invalid'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invalid', 'Invalid'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
    ]
