# Generated by Django 2.2.5 on 2019-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191005_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='appstore_bundle_id',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='google_play_api_key',
            field=models.CharField(default='', max_length=256, verbose_name='Google Play API Key'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='google_play_bundle_id',
            field=models.CharField(default='', max_length=256, verbose_name='Play Market Bundle ID'),
        ),
    ]
