# Generated by Django 2.2.5 on 2019-09-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190928_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appstoreiappurchase',
            old_name='product',
            new_name='appstore_product',
        ),
        migrations.RenameField(
            model_name='googleplayiappurchase',
            old_name='product',
            new_name='google_play_product',
        ),
    ]
