# Generated by Django 2.2.5 on 2019-11-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191120_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='google_play_api_key',
        ),
    ]
