# Generated by Django 2.2.5 on 2019-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191005_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='token',
            field=models.CharField(max_length=256, unique=True, verbose_name='Токен идентификатор сессии'),
        ),
    ]
