# Generated by Django 2.2.5 on 2019-09-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190928_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='purchase_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='googleplayproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
