# Generated by Django 2.2.5 on 2019-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_credentials_google_play_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplayproduct',
            name='is_rewarded_product',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
