# Generated by Django 2.2.5 on 2019-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191005_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='auth_token',
            field=models.CharField(default='', max_length=256, unique=True, verbose_name='Токен идентификатор сессии'),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='token',
            field=models.CharField(max_length=256, unique=True, verbose_name='Токен устройства'),
        ),
    ]
