# Generated by Django 2.2.5 on 2019-09-28 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190928_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
