# Generated by Django 2.2.5 on 2019-11-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_googleplayproduct_is_rewarded_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='device_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_appstoreiappurchase_related', related_query_name='api_appstoreiappurchases', to='api.DeviceSession'),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='device_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_googleplayiappurchase_related', related_query_name='api_googleplayiappurchases', to='api.DeviceSession'),
        ),
    ]
