# Generated by Django 2.2.5 on 2019-10-12 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191005_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('inprogress', 'In progress'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('inprogress', 'In progress'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
    ]
