# Generated by Django 2.2.5 on 2019-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191125_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='previous_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invalid', 'Invalid'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='unknown', max_length=16, verbose_name='Validation status before validation occured'),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='previous_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('invalid', 'Invalid'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='unknown', max_length=16, verbose_name='Validation status before validation occured'),
        ),
    ]
