# Generated by Django 2.2.5 on 2019-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_credentials_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
        migrations.AlterField(
            model_name='appstoreiappurchase',
            name='type',
            field=models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16, verbose_name='Type: reward video or purchase'),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unknown', max_length=16, verbose_name='Validation status'),
        ),
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='type',
            field=models.CharField(choices=[('video', 'Reward Video'), ('purchase', 'Purchase')], default='purchase', max_length=16, verbose_name='Type: reward video or purchase'),
        ),
        migrations.AlterField(
            model_name='googleplayproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=256, verbose_name='IAP SKU (Product ID)'),
        ),
    ]
