# Generated by Django 2.2.5 on 2019-10-12 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191012_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplayproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
