# Generated by Django 2.2.5 on 2019-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191125_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstoreiappurchase',
            name='payload',
            field=models.TextField(blank=True, verbose_name='Any additional metadata for Purchase'),
        ),
        migrations.AddField(
            model_name='googleplayiappurchase',
            name='payload',
            field=models.TextField(blank=True, verbose_name='Any additional metadata for Purchase'),
        ),
        migrations.AddField(
            model_name='googleplayproduct',
            name='is_test',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
