# Generated by Django 2.2.5 on 2019-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191126_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleplayiappurchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
