# Generated by Django 2.2.5 on 2019-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesession',
            name='auth_token',
            field=models.CharField(db_index=True, default='', max_length=256, unique=True, verbose_name='Токен идентификатор сессии'),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='token',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Токен устройства'),
        ),
    ]
