# Generated by Django 2.2.5 on 2020-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191201_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplayproduct',
            name='is_admob_rewarded_ssv',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
