# Generated by Django 2.2.5 on 2020-02-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pushmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='schedule',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
