# Generated by Django 2.2.5 on 2020-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200213_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushmessage',
            name='schedule',
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='friday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='monday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='saturday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='sunday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='thursday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='tuesday',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='wednesday',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
