# Generated by Django 2.2.5 on 2020-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200217_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='friday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='monday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Monday'),
        ),
    ]
