# Generated by Django 2.2.5 on 2020-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200217_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationqueueitem',
            name='meta',
            field=models.TextField(blank=True, default='', verbose_name='Internal field'),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pushmessage',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
