# Generated by Django 2.2.5 on 2020-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200217_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationqueueitem',
            name='data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
