# Generated by Django 2.2.5 on 2019-10-02 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('quotes', '0001_initial'), ('quotes', '0002_auto_20190927_1516'), ('quotes', '0003_auto_20190927_1651'), ('quotes', '0004_auto_20190927_1749'), ('quotes', '0005_auto_20190928_1319'), ('quotes', '0006_auto_20190928_1321'), ('quotes', '0007_auto_20190928_1734'), ('quotes', '0008_auto_20191001_1629'), ('quotes', '0009_auto_20191002_1144'), ('quotes', '0010_remove_product_app_store_product'), ('quotes', '0011_profile_nickname'), ('quotes', '0012_auto_20191002_1201'), ('quotes', '0013_auto_20191002_1208'), ('quotes', '0014_auto_20191002_1353'), ('quotes', '0015_auto_20191002_1517'), ('quotes', '0016_auto_20191002_1522')]

    initial = True

    dependencies = [
        ('api', '0003_auto_20190928_1319'),
        ('api', '0001_initial'),
        ('api', '0009_auto_20190928_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'автор цитат',
                'verbose_name_plural': 'авторы цитат',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sessions', models.ManyToManyField(to='api.DeviceSession')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('nickname', models.CharField(default='Пан Инкогнито', max_length=256)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='QuoteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Раздела')),
                ('available_by_default', models.BooleanField(default=False)),
                ('available_to_users', models.ManyToManyField(to='quotes.Profile')),
                ('event_description', models.TextField(default='')),
                ('event_due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_title', models.CharField(default='', max_length=256)),
                ('is_event', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'категория цитат',
                'verbose_name_plural': 'категории цитат',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Текст цитаты')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteAuthor')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteCategory')),
            ],
            options={
                'verbose_name': 'цитата',
                'verbose_name_plural': 'цитаты',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_id', models.CharField(max_length=256, verbose_name='Имя иконки в приложении')),
                ('title', models.CharField(max_length=256)),
                ('received_text', models.TextField(default='')),
                ('description_text', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_win_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Темы')),
                ('on_complete_achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement')),
            ],
        ),
        migrations.RenameField(
            model_name='quotecategory',
            old_name='available_by_default',
            new_name='is_payable',
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='price_to_unlock',
            field=models.BigIntegerField(default=0, verbose_name='Стоимость открытия категории если она платная'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название Категории'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Раздела')),
                ('on_complete_achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Section'),
        ),
        migrations.CreateModel(
            name='GameBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_profile_balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.GameBalance'),
        ),
        migrations.CreateModel(
            name='BalanceRechargeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_title', models.CharField(max_length=256, verbose_name='Название для админки')),
                ('balance_recharge', models.IntegerField(default=1, verbose_name='Сумма пополнения баланса')),
                ('google_play_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct')),
            ],
            options={
                'verbose_name': 'IAP продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='available_to_users',
            field=models.ManyToManyField(to='quotes.Profile', verbose_name='Профили пользователей которым доступна категория'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='is_payable',
            field=models.BooleanField(default=False, verbose_name='Категория платная?'),
        ),
    ]
