# Generated by Django 2.2.5 on 2019-10-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_squashed_0003_remove_quotecategory_available_to_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotecategory',
            old_name='available_to_users2',
            new_name='available_to_users',
        ),
    ]
