# Generated by Django 2.2.5 on 2019-10-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191002_1536'),
        ('quotes', '0001_squashed_0016_auto_20191002_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUnlockPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_to_unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteCategory')),
                ('google_play_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayIAPPurchase')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Profile')),
            ],
            options={
                'verbose_name': 'Покупка доступа к категории',
                'verbose_name_plural': 'Покупки доступов к категориям',
            },
        ),
    ]
