# Generated by Django 2.2.5 on 2019-09-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'автор цитат',
                'verbose_name_plural': 'авторы цитат',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'цитата', 'verbose_name_plural': 'цитаты'},
        ),
        migrations.AlterModelOptions(
            name='quotecategory',
            options={'verbose_name': 'категория цитат', 'verbose_name_plural': 'категории цитат'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteAuthor'),
        ),
    ]
