# Generated by Django 2.2.5 on 2019-09-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190927_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login_ipaddr',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteAuthor'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteCategory'),
        ),
    ]
