# Generated by Django 2.2.5 on 2019-10-13 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_profile_last_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancerechargeproduct',
            options={'verbose_name': 'Продукт «Начисление монеток»', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description_text',
            field=models.TextField(default='', verbose_name='Описание достижения для юзера'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='received_text',
            field=models.TextField(default='', verbose_name='Текст для юзера при вручении ему достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='achievementreceiving',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Achievement', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='achievementreceiving',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='achievementreceiving',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда получено достижение'),
        ),
        migrations.AlterField(
            model_name='balancerechargeproduct',
            name='admin_title',
            field=models.CharField(max_length=256, verbose_name='Название продукта для юзера'),
        ),
        migrations.AlterField(
            model_name='balancerechargeproduct',
            name='google_play_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct', verbose_name='Соответствующий продукт в Google Play'),
        ),
        migrations.AlterField(
            model_name='categoryunlockpurchase',
            name='category_to_unlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.QuoteCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categoryunlockpurchase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='categoryunlockpurchase',
            name='google_play_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayIAPPurchase', verbose_name='Соотв. покупка в Google Play'),
        ),
        migrations.AlterField(
            model_name='categoryunlockpurchase',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Profile', verbose_name='Юзер'),
        ),
        migrations.AlterField(
            model_name='categoryunlockpurchase',
            name='type',
            field=models.CharField(choices=[('null_unlock', '!! не использовать !!'), ('unlock_for_coins', 'Анлок за игровые монеты'), ('unlock_by_purchase', 'Анлок за покупку')], default='null_unlock', max_length=32, verbose_name='Тип анлока (за монеты или за покупку)'),
        ),
        migrations.AlterField(
            model_name='gamebalance',
            name='initial_profile_balance',
            field=models.BigIntegerField(default=0, verbose_name='Начальный баланс монет у юзера'),
        ),
        migrations.AlterField(
            model_name='gamebalance',
            name='reward_per_doubleup',
            field=models.BigIntegerField(default=5, verbose_name='Вознаграждение за double-up'),
        ),
        migrations.AlterField(
            model_name='gamebalance',
            name='reward_per_level_completion',
            field=models.BigIntegerField(default=5, verbose_name='Вознаграждение за решение цитаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_sessions',
            field=models.ManyToManyField(to='api.DeviceSession', verbose_name='Сессии устройств'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней активности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Пан Инкогнито', max_length=256, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.GameBalance', verbose_name='Соответствующий объект Игрового баланса'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteAuthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.QuoteCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement', verbose_name='Достижение выдаваемое при прохождении'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание события для юзера'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата окончания события'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_icon',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Иконка события'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_win_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_event_complete_achievement', to='quotes.Achievement', verbose_name='Достижение, вручаемое при прохождении события'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Название иконки'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Это событие?'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement', verbose_name='Достижение выдаваемое при прохождении'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='section',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement', verbose_name='Достижение выдаваемое при прохождении'),
        ),
        migrations.AlterField(
            model_name='section',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Тема скрыта?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement', verbose_name='Достижение выдаваемое при прохождении'),
        ),
    ]
