# Generated by Django 2.2.5 on 2019-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20191005_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementreceiving',
            options={'verbose_name': 'достижения vs юзеры', 'verbose_name_plural': 'достижения vs юзеры'},
        ),
        migrations.AlterModelOptions(
            name='gamebalance',
            options={'verbose_name': 'игровой баланс', 'verbose_name_plural': 'игровой баланс'},
        ),
        migrations.AddField(
            model_name='quote',
            name='complete_by_users',
            field=models.ManyToManyField(blank=True, related_name='quote_complete_by_users', to='quotes.Profile', verbose_name='Юзеры которые прошли уровень'),
        ),
    ]
