# Generated by Django 2.2.5 on 2019-09-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190927_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteauthor',
            old_name='author',
            new_name='name',
        ),
    ]
