# Generated by Django 2.2.5 on 2019-10-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191009_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='complete_by_users',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='bonus_reward',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='complete_by_users',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='on_complete_achievement',
        ),
        migrations.RemoveField(
            model_name='section',
            name='bonus_reward',
        ),
        migrations.RemoveField(
            model_name='section',
            name='complete_by_users',
        ),
        migrations.RemoveField(
            model_name='section',
            name='on_complete_achievement',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='bonus_reward',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='complete_by_users',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='on_complete_achievement',
        ),
    ]
