# Generated by Django 2.2.5 on 2019-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20191002_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
