# Generated by Django 2.2.5 on 2019-09-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190928_1319'),
        ('quotes', '0004_auto_20190927_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=2, verbose_name='Короткое название языка (en, us, ...)')),
                ('admin_name', models.CharField(max_length=256, verbose_name='Название языка в админке')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='language',
            field=models.ForeignKey(on_delete='Язык категории', to='quotes.QuoteLanguage'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_title', models.CharField(max_length=256, verbose_name='Название')),
                ('app_title', models.CharField(max_length=256, verbose_name='Название для приложения')),
                ('balance_recharge', models.IntegerField(default=1, verbose_name='Сумма пополнения баланса')),
                ('app_store_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AppStoreProduct')),
                ('google_play_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct')),
            ],
        ),
    ]
