# Generated by Django 2.2.5 on 2019-10-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_topic_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
    ]
