# Generated by Django 2.2.5 on 2019-11-17 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20191117_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
