# Generated by Django 2.2.5 on 2019-10-09 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20191009_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategory',
            name='bonus_reward',
            field=models.BigIntegerField(default=0, verbose_name='Бонус монет за прохождение'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='complete_by_users',
            field=models.ManyToManyField(blank=True, related_name='quotes_quotecategory_complete_by_users', related_query_name='quotes_quotecategory_complete_by_users_objs', to='quotes.Profile', verbose_name='Юзеры которые прошли и должны получить вознаграждение'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_win_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_event_complete_achievement', to='quotes.Achievement'),
        ),
    ]
