# Generated by Django 2.2.5 on 2019-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategory',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='quotecategoryimages', verbose_name='Картинка категории 512х512'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='item_image_preview',
            field=models.FileField(blank=True, null=True, upload_to='quotecategoryimages-preview', verbose_name='Превью картинки категории 256х256'),
        ),
    ]
