# Generated by Django 2.2.5 on 2019-10-03 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20191003_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'достижение', 'verbose_name_plural': 'достижения'},
        ),
        migrations.AlterModelOptions(
            name='quotecategory',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='available_to_users',
            field=models.ManyToManyField(blank=True, to='quotes.Profile', verbose_name='Профили пользователей которым доступна категория'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='event_win_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='price_to_unlock',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Стоимость открытия категории если она платная'),
        ),
    ]
