# Generated by Django 2.2.5 on 2019-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20191117_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryunlockpurchase',
            name='status',
            field=models.CharField(choices=[('unknown', 'Неизвестно (только что создан?)'), ('complete', 'Успешно обработан'), ('error', 'Ошибка')], default='unknown', max_length=64),
        ),
    ]
