# Generated by Django 2.2.5 on 2019-10-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20191003_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='icon_id',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_icon',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='on_complete_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_complete_achievement', to='quotes.Achievement'),
        ),
        migrations.CreateModel(
            name='AchievementReceiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='opened_by_users',
            field=models.ManyToManyField(blank=True, through='quotes.AchievementReceiving', to='quotes.Profile', verbose_name='Профили пользователей которые открыли ачивку'),
        ),
    ]
