# Generated by Django 2.2.5 on 2019-09-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20190928_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'IAP продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='app_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='app_store_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.AppStoreProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='google_play_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GooglePlayProduct'),
        ),
    ]
