# Generated by Django 2.2.5 on 2019-10-12 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_categoryunlockpurchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancerechargeproduct',
            name='admin_title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='balancerechargeproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
