# Generated by Django 2.2.5 on 2019-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20190928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_title',
            field=models.CharField(max_length=256, verbose_name='Название для админки'),
        ),
    ]
