# Generated by Django 2.2.5 on 2019-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20191004_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebalance',
            name='reward_per_doubleup',
            field=models.BigIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gamebalance',
            name='reward_per_level_completion',
            field=models.BigIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quote',
            name='order_in_category',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Порядковый номер уровня в категории'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='bonus_reward',
            field=models.BigIntegerField(default=0, verbose_name='Бонус монет за прохождение категории, если есть'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='complete_by_users',
            field=models.ManyToManyField(blank=True, related_name='category_complete_by_users', to='quotes.Profile', verbose_name='Юзеры которые прошли категорию'),
        ),
        migrations.AddField(
            model_name='section',
            name='bonus_reward',
            field=models.BigIntegerField(default=0, verbose_name='Бонус монет за прохождение раздела, если есть'),
        ),
        migrations.AddField(
            model_name='section',
            name='complete_by_users',
            field=models.ManyToManyField(blank=True, related_name='section_complete_by_users', to='quotes.Profile', verbose_name='Юзеры которые прошли секцию'),
        ),
        migrations.AddField(
            model_name='topic',
            name='bonus_reward',
            field=models.BigIntegerField(default=0, verbose_name='Бонус монет за прохождение Темы, если есть'),
        ),
        migrations.AddField(
            model_name='topic',
            name='complete_by_users',
            field=models.ManyToManyField(blank=True, related_name='topic_complete_by_users', to='quotes.Profile', verbose_name='Юзеры которые прошли тему'),
        ),
    ]
