# Generated by Django 2.2.5 on 2019-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategory',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Категория опубликована?'),
        ),
    ]
