# Generated by Django 2.2.5 on 2019-10-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20191001_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Темы')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='language',
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название Раздела'),
        ),
        migrations.DeleteModel(
            name='QuoteLanguage',
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Topic'),
        ),
    ]
