# Generated by Django 2.2.5 on 2019-11-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quotecategory_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Раздел (секция) опубликован?'),
        ),
    ]
