# Generated by Django 2.2.5 on 2019-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_section_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Тема опубликована?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Тема опубликована?'),
        ),
    ]
