# Generated by Django 2.2.5 on 2019-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_remove_product_app_store_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Пан Инкогнито', max_length=256),
        ),
    ]
