# Generated by Django 2.2.5 on 2019-10-02 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_profile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_id', models.CharField(max_length=256, verbose_name='Имя иконки в приложении')),
                ('title', models.CharField(max_length=256)),
                ('received_text', models.TextField(default='')),
                ('description_text', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='available_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='available_to_users',
            field=models.ManyToManyField(to='quotes.Profile'),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='event_win_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
        migrations.AddField(
            model_name='topic',
            name='on_complete_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement'),
        ),
    ]
