# Generated by Django 2.2.5 on 2019-11-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20191120_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='hidden',
        ),
    ]
