# Generated by Django 2.2.5 on 2019-10-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20191002_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotecategory',
            old_name='available_by_default',
            new_name='is_payable',
        ),
        migrations.RemoveField(
            model_name='quotecategory',
            name='topic',
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='price_to_unlock',
            field=models.BigIntegerField(default=0, verbose_name='Стоимость открытия категории если она платная'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название Категории'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Раздела')),
                ('on_complete_achievement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Achievement')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='quotecategory',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.Section'),
        ),
    ]
