# Generated by Django 2.2.5 on 2019-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_remove_topic_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancerechargeproduct',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показывать как самый выгодный?'),
        ),
        migrations.AlterField(
            model_name='quotecategory',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Категория опубликована?'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Раздел (секция) опубликован?'),
        ),
    ]
