# Generated by Django 2.2.5 on 2019-10-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_auto_20191002_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_profile_balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quotes.GameBalance'),
        ),
    ]
