# Generated by Django 2.2.5 on 2019-11-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_auto_20191121_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1000, verbose_name='Порядок сортировки: чем ниже значение, тем выше Категория в Разделе'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1000, verbose_name='Порядок сортировки: чем ниже значение, тем выше Секция в Теме'),
        ),
    ]
