# Generated by Django 2.2.5 on 2019-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20191121_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='achievements', verbose_name='Картинка 512х512'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='item_image_preview',
            field=models.FileField(blank=True, null=True, upload_to='achievements-preview', verbose_name='Превью картинки 256х256'),
        ),
        migrations.AddField(
            model_name='balancerechargeproduct',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='rechargeproducts', verbose_name='Картинка 512х512'),
        ),
        migrations.AddField(
            model_name='balancerechargeproduct',
            name='item_image_preview',
            field=models.FileField(blank=True, null=True, upload_to='rechargeproducts-preview', verbose_name='Превью картинки 256х256'),
        ),
    ]
