# Generated by Django 2.2.5 on 2019-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_auto_20191126_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_from_rank',
            field=models.BooleanField(blank=True, default=False, verbose_name='Скрыть из таблицы топа?'),
        ),
    ]
