# Generated by Django 2.2.5 on 2019-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_profile_hide_from_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
