# Generated by Django 2.2.5 on 2019-11-27 19:34

from django.db import migrations, models
import django.db.models.deletion
import quotes.itemimage
import quotes.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_auto_20191127_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('normal', 'Normally completed level.'), ('skipped', 'Skipped the level.')], default='normal', max_length=16)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Profile')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='CoinProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_title', models.CharField(max_length=256, verbose_name='Название продукта для юзера')),
                ('is_featured', models.BooleanField(blank=True, default=False, verbose_name='Показывать как самый выгодный?')),
                ('item_image', models.FileField(blank=True, null=True, upload_to='rechargeproducts', verbose_name='Картинка 512х512')),
                ('item_image_preview', models.FileField(blank=True, null=True, upload_to='rechargeproducts-preview', verbose_name='Превью картинки 256х256')),
                ('coin_price', models.PositiveIntegerField(default=0, verbose_name='Стоимость в монетах для юзера')),
                ('kind', models.CharField(choices=[('AUTHOR', 'Подсказка Автора'), ('NEXT_WORD', 'Подсказка Следующего слова'), ('SKIP_LEVEL', 'Пропуск уровня')], max_length=16, verbose_name='Тип продукта для моб. клиента')),
                ('scope_tags', models.ManyToManyField(blank=True, to='quotes.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, quotes.models.ProductFlow, quotes.itemimage.ItemWithImageMixin),
        ),
        migrations.AddField(
            model_name='quote',
            name='complete_by_users2',
            field=models.ManyToManyField(blank=True, related_name='quotes_quote_completion_by_users', related_query_name='quotes_quote_complete_by_users_objs', through='quotes.QuoteCompletion', to='quotes.Profile', verbose_name='Юзеры которые прошли и должны получить вознаграждение'),
        ),
    ]
