# Generated by Django 2.2.5 on 2019-11-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20191127_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinproduct',
            options={'verbose_name': 'Продукт-бустер', 'verbose_name_plural': 'Продукты-бустеры доступные за монеты'},
        ),
    ]
