# Generated by Django 2.2.5 on 2019-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_auto_20191129_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description_text',
            field=models.TextField(blank=True, default='', verbose_name='Описание достижения для юзера'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=256, verbose_name='Имя иконки в приложении'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='received_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст для юзера при вручении ему достижения'),
        ),
    ]
