# Generated by Django 2.2.5 on 2019-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_auto_20191201_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecategory',
            name='level_bonus_reward',
            field=models.BigIntegerField(default=10, verbose_name='Бонус за прохождение Цитаты в этой категории'),
        ),
    ]
