# Generated by Django 2.2.5 on 2019-11-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0003_auto_20191013_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRank',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quotes.Profile')),
            ],
        ),
    ]
