# Generated by Django 2.2.5 on 2019-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoterank', '0002_auto_20191117_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerank',
            name='total_hints_author_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilerank',
            name='total_hints_next_word_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilerank',
            name='total_hints_skipped_levels_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
